---
description-meta: |
  Este es un libro con un pequeño tutorial de los resultados obtenidos al usar el módulo de Python SeqBreed.
---

## Bienvenido {.unnumbered}

Este es el sitio web del **"Tutorial básico con SeqBreed"**. Aquí encontrará algunos de los resultados obtenidos al realizar mi trabajo de grado del [Máster de Mejora Genética Animal y Biotecnología de la Reproducción](http://www.mastermejorageneticaanimal.es/), específicamente, los resultados obtenidos al usar el módulo de `Python` [`SeqBreed`](https://github.com/miguelperezenciso/SeqBreed).

A lo largo de este tutorial usaré bloques informativos para resaltar algún aspecto importante. Abajo encontrará un ejemplo de los bloques y su significado.

::: {.aclaracion}
Información sobre un tema de interés.
:::

::: {.codigo}
Información sobre una función usada en la codificación.
:::

## Licencia

Esta página web es de uso gratuito y está licenciado bajo la licencia [licencia Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/). Sí tiene alguna inquietud al respecto, por favor informar a los correos jollopezma@unal.edu.co y mperezenciso@gmail.com.
